import { Geist } from 'next/font/google';

import type { Metadata } from 'next';

import './globals.css';

const geist = Geist({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Turborepo',
    description: 'Generated by create turbo',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={geist.className}>{children}</body>
        </html>
    );
}
